In [4]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [7]:
race = pd.read_csv('seikika2.csv', index_col = 0)
X = np.array([race["人気"],race["馬番"],]).T
Y = np.array(race["複勝"])
X

array([[0.23529412, 0.58823529],
       [0.        , 0.11764706],
       [0.11764706, 0.52941176],
       ...,
       [0.70588235, 0.35294118],
       [0.64705882, 0.        ],
       [0.52941176, 0.52941176]])

In [8]:
import sklearn.model_selection
X_train, X_test, Y_train, Y_test = sklearn.model_selection.train_test_split(X,Y)

In [9]:
print(race.corr())

           着順       レース        芝ダ        距離        天候        馬場        馬番  \
着順   1.000000 -0.027343  0.031634 -0.068844 -0.000106  0.002975  0.107754   
レース -0.027343  1.000000 -0.221910  0.111257  0.032705 -0.086623 -0.026878   
芝ダ   0.031634 -0.221910  1.000000 -0.196187 -0.016171  0.207620  0.033891   
距離  -0.068844  0.111257 -0.196187  1.000000 -0.007779 -0.054548 -0.067459   
天候  -0.000106  0.032705 -0.016171 -0.007779  1.000000  0.294882  0.000201   
馬場   0.002975 -0.086623  0.207620 -0.054548  0.294882  1.000000  0.003800   
馬番   0.107754 -0.026878  0.033891 -0.067459  0.000201  0.003800  1.000000   
斤量  -0.091578  0.269987  0.083821  0.129446 -0.013428  0.008665 -0.003982   
単勝   0.465998 -0.114557  0.008603 -0.018526 -0.012397  0.003568  0.058903   
人気   0.589813 -0.027591  0.032804 -0.068851  0.000633  0.003453  0.087036   
馬体重 -0.075837  0.225017  0.202723  0.127655 -0.000411  0.029945 -0.014855   
増減  -0.010507  0.017221  0.000389 -0.013686  0.021883  0.016044 -0.005959   

In [154]:
X_test.shape

(7663, 4)

In [155]:
X_train.shape

(22987, 4)

In [10]:
kaiki = linear_model.LinearRegression()
kaiki.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
print(kaiki.score(X_train,Y_train))

0.185250640744825


In [12]:
print(kaiki.score(X_test,Y_test))

0.1800481748024465


In [143]:
sum = 0
for test in X_test:
    if kaiki.predict(test) < 2:
        if X_test.着順 == 0:
            sum+=100*X_test

kaiki.predict(X_test[60:80])

array([[0.40604369],
       [0.17681102],
       [0.28425857],
       [0.5064236 ],
       [0.51227182],
       [0.39861161],
       [0.3467328 ],
       [0.28189284],
       [0.40323468],
       [0.46046872],
       [0.30116576],
       [0.20440774],
       [0.45896473],
       [0.32214442],
       [0.17326369],
       [0.36943528],
       [0.46083604],
       [0.16989027],
       [0.42001054],
       [0.45526916]])

In [147]:
Y_test.shape

(7663, 1)

In [159]:
Y_test[0]

0.1176470588235294

In [160]:
X_test

array([[0.05882353, 0.05882353, 0.72727273, 0.00387125],
       [0.17647059, 0.17647059, 0.63636364, 0.00818494],
       [0.        , 0.11764706, 0.81818182, 0.00132729],
       ...,
       [0.41176471, 0.76470588, 0.54545455, 0.05054751],
       [0.58823529, 0.23529412, 0.81818182, 0.06957195],
       [0.        , 0.17647059, 0.81818182, 0.00143789]])